### ISSUE TITLE
32bit arm version, please!

### ISSUE THREAD

**Issue by DI555** [macchrome/droidchrome#1]
Please, provide and 32bit arm android version also! There are so much 32bit arm SoCs!
Many thanks in advance!

**Comment by DI555** [comment]
I mean armeabi-v7a 32bit one build, it's so much needed!!!

**Comment by DI555** [comment]
please, reopen this issue, just to be it in todo list !!!

**Comment by macchrome** [comment]
I will keep this version up to date then do occasional releases.

https://github.com/macchrome/droidchrome/releases/download/v84.0.4147.111-r768962-Ungoogled-And64/arm_ChromePublic_HEVC-84.0.4147.111_1.apk
