### ISSUE TITLE
Can I haz argz

### ISSUE THREAD

**Issue by Alex313031** [macchrome/droidchrome#12]
Similar to before, can I have the args and any other changes you might have made for these android releases.

Also, check out my Chromium fork for linux https://github.com/Alex313031/Thorium

And, my ChromiumOS builds with linux firmware/modules, codecs, and extra packages like iotop, sysstat, htop, and sl.
https://github.com/Alex313031/ChromiumOS

**Comment by macchrome** [comment]
HEVC is natively supported on the Android platform.

enable_platform_ac3_eac3_audio
enable_platform_dolby_vision
enable_platform_encrypted_hevc
enable_platform_hevc
enable_platform_hevc_decoding
enable_platform_mpeg_h_audio
================

Additional chrome://flags/ 

>>>[chromium/src › main]
chrome/browser/about_flags.cc


 {"enable-clear-hevc-for-testing",
     flag_descriptions::kEnableClearHevcForTestingName,
     flag_descriptions::kEnableClearHevcForTestingDescription, kOsAll,
     SINGLE_VALUE_TYPE(switches::kEnableClearHevcForTesting)},

>>>[chromium/src › main]
chrome/browser/flag_descriptions.h

extern const char kEnableClearHevcForTestingName[];
extern const char kEnableClearHevcForTestingDescription[];

>>>[chromium/src › main]
chrome/browser/flag_descriptions.cc

const char kEnableClearHevcForTestingName[] = "Enable clear HEVC for testing";
const char kEnableClearHevcForTestingDescription[] =
    "Enables playback of clear (unencrypted) HEVC content for testing purposes. "
    "marmaduke-ungoogled-chromium special measures flag.";
