### ISSUE TITLE
Immediatly crashing on Samsung Galaxy S22 (Exynos)

### ISSUE THREAD

**Issue by madejackson** [macchrome/droidchrome#14]
Hi, I just wanted to let you know that this chromium version does not work on the new Samsung Galaxy S22 (Exynos).

On startup, it crashes immediately. Older Versions (f.e. v91...) does starts, but it won't load any webpage.

Meanwhile it works fine on my old Samsung Galaxy S10e with Exynos.

The official chromium with google does work fine on both devices, though without HEVC-Support.

**Comment by macchrome** [comment]
Rename the package name, with apkeditor pro or equivalent,  to org.chromium.chrome

**Comment by madejackson** [comment]
just tried it, didn't change anything. I used apktools to edit.

**Comment by angelog0** [comment]
The same crash occurs on a Xiaomi Redmi5p with android 8.1, both with 99.0.4844.73 and 99.0.4844.58.

I noticed that when installing the above packages it does not upgrade the previous version of Chromium (97.0.4692.98) but the phone results with TWO Chromium installed! 

I installed Chromium from this repo since (maybe) version 70 series and always upgrade using package from here; never reinstalled from scratch always upgraded..

This is the first time I have to reinstall from scratch.. Indeed reverting to 97.0.4692.98 works.

**Comment by MichaelEFlip** [comment]
Same happens here on Pixel 6 with CalyxOS 3.3.1
Using arm64_ChromePublic_HEVC-99.0.4844.73.apk chromium crashes immediatly after opening. When the device is offline it does **not** crash.

Downgrading to arm64_ChromePublic_HEVC-97.0.4692.98.apk solved the problem. Unfortunately this is only possible via adb with the downgrade option enabled:
`adb install -r -d arm64_ChromePublic_HEVC-97.0.4692.98.apk`

**Comment by macchrome** [comment]
Disable auto-update (and perhaps ad-blocking.)

**Comment by madejackson** [comment]
> Same happens here on Pixel 6 with CalyxOS 3.3.1 Using arm64_ChromePublic_HEVC-99.0.4844.73.apk chromium crashes immediatly after opening. When the device is offline it does **not** crash.
> 
> Downgrading to arm64_ChromePublic_HEVC-97.0.4692.98.apk solved the problem. Unfortunately this is only possible via adb with the downgrade option enabled: `adb install -r -d arm64_ChromePublic_HEVC-97.0.4692.98.apk`

Can Confirm, [arm64_ChromePublic_HEVC-97.0.4692.98.apk](https://github.com/macchrome/droidchrome/releases/download/v97.0.4692.98-r938553-Ungoogled-And64/arm64_ChromePublic_HEVC-97.0.4692.98.apk) did work for me as well.


> Disable auto-update (and perhaps ad-blocking.)

A manually installed .apk cannot auto-update itself, hence there is no such setting. I do not have any ad-block active.

**Comment by macchrome** [comment]
settings ->  about chrome -> allow checking for updates
