### ISSUE TITLE
[BUG] Browser always uses Desktop mode-like view

### ISSUE THREAD

**Issue by HarriBuh** [macchrome/droidchrome#18]
I recently installed this browser and while I'm very happy about the core and security features, I'm encountering the same issues everytime I'm browsing a website again: 
The browser would always use the desktop mode/ view without actually enabling it.

It looks like the app uses the wrong user agent- maybe for security reasons? This is very annoying and makes the app uncomfortable to use.
Is there a way to bypass it?

Correction: This does NOT always happen, just with many sites.

**Comment by weeksco** [comment]
I experience the same issue. It didn't happen with the December v108 release.

**Comment by macchrome** [comment]
https://github.com/macchrome/droidchrome/releases/tag/v109.5414.128-M109.0.5414.128-r1070088-Ungoogled-And64

Viewport as noted!
