### ISSUE TITLE
Incomplete hide of tab strip when bottom toolbar enable

### ISSUE THREAD

**Issue by mrxyzl** [macchrome/droidchrome#19]
Hello , on the latest build, I found this bug where the tab strip still show an upper part when scrolling.

Check the screen shot:

![Screenshot_20230306_135335_Chromium](https://user-images.githubusercontent.com/91355555/223039652-a4b40a94-8d01-4676-8d74-5b9596789830.jpg)
![Screenshot_20230306_135331_Chromium](https://user-images.githubusercontent.com/91355555/223039669-fec372b7-43c2-4054-989c-09a34fde4c0f.jpg)

**Comment by macchrome** [comment]
Experimental feature, user discretion required.
