### ISSUE TITLE
Custom filter lists is invisible

### ISSUE THREAD

**Issue by johnjupiter32** [macchrome/droidchrome#21]
As the title suggests, when I copy a filter list and add it to Settings/Ad blocking/More blocking options/Custom filter lists, it's displayed but when I exit that section and come back to it again it no longer displays anything even though I have added a few filters. However, if I add a new filter list, the previously added lists are again shown so long as I don't leave that section.

**Comment by macchrome** [comment]
Download Uazo's version version. If the problem persists inform Uazo. Adblock Pro is a work in progress.
