### ISSUE TITLE
Weird issue(s) when installing alongside bromite

### ISSUE THREAD

**Issue by pitsi** [macchrome/droidchrome#22]
Preface: I have been a bromite user for the last ~3 years and lately I am looking for another chromium based browser to replace it... sometime in the future.
I discovered your chromium build ~2 weeks ago, when it was on v111.x, and I installed it the way I always do, via adb (`adb install blablabla.apk`). And a week later, I discovered that someone makes development packages for bromite, here
https://github.com/uazo/bromite-buildtools

As expected, when new versions came out for both browsers, I downloaded and installed the new apks. And here starts the wierd stuff: none of the 2 browsers mentions the correct version in either `chrome://version` (screenshots below) or in the app's info page!

For simplicity reasons, the following are the outputs of `apkinfo` (info from apk file downloaded locally) and `adb shell dympsys package` (info from the os)  for each one.
Chomium
```
$ apkinfo arm64_ChromePublic_HEVC-112.0.5615.62.apk 
APK: arm64_ChromePublic_HEVC-112.0.5615.62.apk
App name: Chromium
Package: org.chromium.chrome.stable
Version name: 112.0.5615.62
Version code: 561506215

$ adb shell dumpsys package org.chromium.chrome.stable | grep version
    versionCode=561506215 minSdk=24 targetSdk=33
    versionName=112.0.5615.62
```
![Screenshot_20230409-142140](https://user-images.githubusercontent.com/5880037/230769828-bdc59cb5-52f4-4415-8a8a-bcf7a108ddb8.png)

Bromite
```
$ apkinfo arm64_ChromePublic.apk 
APK: arm64_ChromePublic.apk
App name: Chromium
Package: org.bromite.bromite.dev
Version name: 112.0.5615.48
Version code: 561504815

$ adb shell dumpsys package org.bromite.bromite.dev | grep version
    versionCode=561504815 minSdk=24 targetSdk=33
    versionName=112.0.5615.48
```
![Screenshot_20230409-142107](https://user-images.githubusercontent.com/5880037/230769861-8b1a9aa7-9194-4fba-ad8b-71312f83c55a.png)

Any idea why?

**Comment by macchrome** [comment]
I have no idea why.  Perhaps the chromium/bromite  version is being spoofed.

**Comment by pitsi** [comment]
What does that mean? I will try removing chromium and updating bromite to see what happens.

---edit
On second thought, I will ask at the bromite's development package repo.
