### ISSUE TITLE
Adblocking not working on the latest v113 build

### ISSUE THREAD

**Issue by driftywinds** [macchrome/droidchrome#25]
No ads are blocked in the latest build, and all ads are visible on pages they weren't before. Is there a possibility for a fix?

**Comment by negasis** [comment]
Can confirm, this is what is happening to me too

**Comment by macchrome** [comment]
The firewall is enabled by default and the standard ad blocker auto-update is blocked by the firewall. I use the ad lists at  https://github.com/xarantolus/filtrite/releases  from local storage.

Clear the browsing data, configure the ad blocker(s) correctly, and lower the firewall.

The combination of the two ad blockers works extremely well.

**Comment by driftywinds** [comment]
> The firewall is enabled by default and the standard ad blocker auto-update is blocked by the firewall. I use the ad lists at https://github.com/xarantolus/filtrite/releases from local storage.
> 
> Clear the browsing data, configure the ad blocker(s) correctly, and lower the firewall.
> 
> The combination of the two ad blockers works extremely well.

Sorry, which firewall are you referring to?

**Comment by macchrome** [comment]
chrome://flags/#enable-firewall
