### ISSUE TITLE
Aw, Snap - www.dn.pt

### ISSUE THREAD

**Issue by Provider-1** [macchrome/droidchrome#27]
Droidchrome UI crashes with "Aw, Snap!" in https://www.dn.pt 
Steps to reproduce: Visit provided link.

**Comment by macchrome** [comment]
The same behaviour is exhibited in Uazo;s Window's build.

Tell dn.pt to make their html compliant.

**Comment by macchrome** [comment]
Problem fixed:

https://github.com/macchrome/droidchrome/releases/download/v114.5735.213-M114.0.5735.213-r1135570-Ungoogled-And64/arm64_ChromePublic_HEVC-114.0.5735.213.apk
