### ISSUE TITLE
Broken Cloudfare CAPTCHA

### ISSUE THREAD

**Issue by ZaNYAshlin** [macchrome/droidchrome#28]
I can't pass Cloudfare CAPTCHA only in this browser but other browsers like Bromite, Chrome, Firefox can

Chromium (failure):
![Screenshot_2023-08-04-10-59-47-63_feec35198c190ef76561fa9909ddd5b1.jpg](https://github.com/macchrome/droidchrome/assets/74340112/6e9c52f8-ff58-4823-8134-c159eb897ad7)

Bromite (success):
![Screenshot_2023-08-04-10-58-52-96_ed7821ed99ee442dec4ede205e7971d6.jpg](https://github.com/macchrome/droidchrome/assets/74340112/a8249010-04a3-4db9-8303-12a10a47d2e3)

Firefox (success):
![Screenshot_2023-08-04-11-01-07-75_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/macchrome/droidchrome/assets/74340112/2bfc6eb2-4878-4611-be12-96e037152957)

**Comment by macchrome** [comment]
Problem noted.
