### ISSUE TITLE
Fork of Cromite?

### ISSUE THREAD

**Issue by ksant0s** [macchrome/droidchrome#29]
Is this your build based on Cromite with additional optimizations? I mean does your build has all the Cromite's patches? I saw you have written derived from Cromite with commit link in release note. I am forced to ask here, as you haven't enabled discussion section.

**Comment by Universalizer** [comment]
Hello, Macchrome, Well-Wishes,

Of Course, Discussion section will be welcome.
As discussions `could not be done` in Issues section.

Personal request to `change app label name from` 'Chromium' to something distinct,

App's license mention herein github repo.
