### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Universalizer** [macchrome/droidchrome#30]
https://github.com/macchrome/droidchrome/releases/tag/v116.5845.172-M116.0.5845.172-r1160321-Ungoogled-And64

**Noticed**
> `OS Android 64-bit: Only for Oreo 8.1.0+ & Pie 9 & 10`

Question :-
Can Android 11+ user can use these Browser build ?
Thanks for the great good work.

**Comment by macchrome** [comment]
Yes , Android 11+ users can use this browser build - the minimum usage requirement is Android 8.1.0
