### ISSUE TITLE
Query whether 'subresource_filter' size supporting 50MB.

### ISSUE THREAD

**Issue by Universalizer** [macchrome/droidchrome#31]
Title,
Relating :-
https://github.com/Universalizer/Universaliser_Filters/discussions/4
And
https://github.com/Universalizer/Universaliser_Filters/discussions/6

**So, these query is important for me. Or do i need any corrections in my poll**
Thank You.

**Comment by macchrome** [comment]
https://github.com/uazo/cromite/commit/90270433016dca70e08c823cc770d8f1891ecc93 which with a modicum of research you could've found yourself!

**Comment by Universalizer** [comment]
I do know these https://github.com/uazo/cromite/blob/d3d806286434d11e526bb01b4138997805dced9d/build/patches/Bromite-subresource-adblocker.patch#L1149
Before my discussion in https://github.com/Universalizer/Universaliser_Filters/discussions/4

I'm just asking for `droidchrome` also 50MB ? Like upstream Cromite.
