### ISSUE TITLE
multilingual google search

### ISSUE THREAD

**Issue by macciek-k** [macchrome/droidchrome#32]
There is "Google in English" search engine, but I would like to have Google search engine that detects system language of the phone (or at least to have an option to add custom search engine, as it is on desktop Chromium)

**Comment by macchrome** [comment]
I replaced Google with "No Search". 

I'm not particularly interested in encouraging, promoting or facilitating  the further usage of the Google search engine.

**Comment by sankhababu** [comment]
> I replaced Google with "No Search".
> 
> I'm not particularly interested in encouraging, promoting or facilitating the further usage of the Google search engine.

That's reasonable. In that case, could you add Brave and StartPage as inbuilt option?
