### ISSUE TITLE
CSS a:visited does't work in droidchrome

### ISSUE THREAD

**Issue by Ajaja** [macchrome/droidchrome#34]
How to reproduce:
Check that history settings is on (90 days e.g.)
Open https://developer.mozilla.org/en-US/docs/Web/CSS/:visited  
Visit some link in the example (MDN Web Docs e.g.)
Return to the page - the style of the visited link doesn't change.

**Comment by macchrome** [comment]
Desirable behaviour as far as I'm concerned.

**Comment by Ajaja** [comment]
Is the different (normal) behavior in winchrome desirable too?
