### ISSUE TITLE
Last release doesn't update older releases

### ISSUE THREAD

**Issue by juxuanu** [macchrome/droidchrome#6]
Scenario: trying to update with the last release having the 2nd most recent one already installed.
Problem: the last release is installed as a separate app, not as an update. This creates two Chromium apps.

Android 10.

**Comment by Glennmen** [comment]
I currently also experienced this issue.
I had 83.0.4103.101 installed and updated to 84.0.4147.111.

Any reason why this is happening?

**Comment by Glennmen** [comment]
@macchrome Is it possible to give an explanation why the package ID has changed in newer versions. This is currently a blocking issue for us to be able to roll out the updated version.
